@host=http://localhost:8080

### Criar usuário

POST {{host}}/users
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@email.com",
  "password": "123456"
}

###

### Login

POST {{host}}/login
Content-Type: application/json

{
  "email": "admin@email.com",
  "password": "123456"
}